In [1]:
#importing  Libraries

In [2]:
import numpy as np
import pandas as pd

In [ ]:
pip install tensorflow


In [6]:
from tensorflow.keras import datasets

In [10]:
(x_train,y_train),(x_test,y_test)=datasets.mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 3s 0us/step


In [14]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [16]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [18]:
x_train.shape

(60000, 28, 28)

In [20]:
x_test.shape

(10000, 28, 28)

In [22]:
width,height=28,28
input_shape=(width,height,1)

In [24]:
input_shape

(28, 28, 1)

In [32]:
x_train=x_train.reshape(x_train.shape[0],height,width,1)
x_test=x_test.reshape(x_test.shape[0],height,width,1)

In [34]:
x_train.shape

(60000, 28, 28, 1)

In [36]:
y_train.shape

(60000,)

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_val,y_train,y_val=train_test_split(x_train,y_train,test_size=0.1)

In [40]:
len(x_val)

6000

In [42]:
x_train=(x_train-x_train.mean())/x_train.std()
x_val=(x_val-x_val.mean())/x_val.std()
x_test=(x_test-x_test.mean())/x_test.std()

In [44]:
x_train

array([[[[-0.42383584],
         [-0.42383584],
         [-0.42383584],
         ...,
         [-0.42383584],
         [-0.42383584],
         [-0.42383584]],

        [[-0.42383584],
         [-0.42383584],
         [-0.42383584],
         ...,
         [-0.42383584],
         [-0.42383584],
         [-0.42383584]],

        [[-0.42383584],
         [-0.42383584],
         [-0.42383584],
         ...,
         [-0.42383584],
         [-0.42383584],
         [-0.42383584]],

        ...,

        [[-0.42383584],
         [-0.42383584],
         [-0.42383584],
         ...,
         [-0.42383584],
         [-0.42383584],
         [-0.42383584]],

        [[-0.42383584],
         [-0.42383584],
         [-0.42383584],
         ...,
         [-0.42383584],
         [-0.42383584],
         [-0.42383584]],

        [[-0.42383584],
         [-0.42383584],
         [-0.42383584],
         ...,
         [-0.42383584],
         [-0.42383584],
         [-0.42383584]]],


       [[[-0.42383584],


In [46]:
y_train

array([8, 0, 8, ..., 0, 5, 6], dtype=uint8)

In [48]:
from tensorflow import keras

In [50]:
num_labels=10
y_train=keras.utils.to_categorical(y_train)

In [52]:
y_train

array([[0., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [56]:
y_val=keras.utils.to_categorical(y_val)
y_test=keras.utils.to_categorical(y_test)

In [58]:
#MODEL

In [64]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Flatten,Input,Conv2D,MaxPooling2D,AveragePooling2D

In [74]:
model = Sequential()

model.add(Conv2D(6, kernel_size=(5,5), strides=(1,1), activation='tanh', input_shape=(28,28,1)))
model.add(AveragePooling2D(pool_size=(2,2), strides=(1,1)))
model.add(Conv2D(16, kernel_size=(5,5), strides=(1,1), activation='tanh'))
model.add(AveragePooling2D(pool_size=(2,2), strides=(2,2)))
model.add(Conv2D(120, kernel_size=(5,5), strides=(1,1), activation='tanh'))
model.add(Flatten())
model.add(Dense(84, activation='tanh'))
model.add(Dense(num_labels, activation='softmax'))

In [78]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_2 (Conv2D)               │ (None, 24, 24, 6)      │           156 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ average_pooling2d               │ (None, 23, 23, 6)      │             0 │
│ (AveragePooling2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 19, 19, 16)     │         2,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ average_pooling2d_1             │ (None, 9, 9, 16)       │             0 │
│ (AveragePooling2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 5, 5, 120)      │        48,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 3000)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 84)             │       252,084 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │           850 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 303,626 (1.16 MB)

 Trainable params: 303,626 (1.16 MB)

 Non-trainable params: 0 (0.00 B)

In [82]:
model.compile(loss=keras.losses.categorical_crossentropy,optimizer='adam',metrics=['accuracy'])

In [84]:
history=model.fit(x_train,y_train,batch_size=32,epochs=5,verbose=1,validation_data=(x_val,y_val))

Epoch 1/5
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.9052 - loss: 0.3210 - val_accuracy: 0.9628 - val_loss: 0.1178
Epoch 2/5
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.9698 - loss: 0.1007 - val_accuracy: 0.9760 - val_loss: 0.0840
Epoch 3/5
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - accuracy: 0.9763 - loss: 0.0790 - val_accuracy: 0.9727 - val_loss: 0.0890
Epoch 4/5
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - accuracy: 0.9794 - loss: 0.0690 - val_accuracy: 0.9783 - val_loss: 0.0722
Epoch 5/5
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - accuracy: 0.9811 - loss: 0.0647 - val_accuracy: 0.9803 - val_loss: 0.0695


In [86]:
score=model.evaluate(x_test,y_test,verbose=1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9798 - loss: 0.0667


In [88]:
score

[0.053238075226545334, 0.9840999841690063]